name: Build Modules
on: 
  workflow_call:
  workflow_dispatch:
  push:
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
		  
      - name: Build Modules/APKs
        run: |
          chmod +x ./run.sh
          ./run.sh
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: update
          skip_checkout: true
          file_pattern: coocaa.m3u8 vthanh.m3u8
          commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
