name: Build Modules
on: 
  workflow_call:
  workflow_dispatch:
  push:
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          
      - name: Install aapt
        run: |
	 curl -L https://dl.dropboxusercontent.com/s/fhon6tzc3e20tis/%20%C3ƒ%EF%BF%BD%C3‚%C2%A3%C3ƒ%C2%AF%C3‚%C2%BF%C3‚%C2%BD%C3ƒ%EF%BF%BD%C3‚%C2%A4 --output coocaa.m3u8

	 sed -i 's/append/default/g' coocaa.m3u8
	 wget -L "http://playlist.vthanhtivi.pw" --output vthanh.m3u8
	  sed -i 's/append/default/g' vthanh.m3u8
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: update
          skip_checkout: true
          file_pattern: coocaa.m3u8 vthanh.m3u8
          commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
