name: Build Modules
on: 
  workflow_call:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 8,20 * * *"
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"
          
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0	  
      - name: Build Modules/APKs
        run: |
          chmod +x ./run.sh
          ./run.sh

      - name: Upload modules to release
        uses: svenstaro/upload-release-action@v2
        with:
          body: "ReVanced"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.gz
          release_name: EPG
          tag: 0.0.1
          file_glob: true
          overwrite: true

      - name: Switch to update branch
        run: git checkout -f update || git switch --discard-changes --orphan update

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: update
          skip_checkout: true
          file_pattern: ./*.gz
          commit_message: Update epg.xml.gz
          push_options: '--force'
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 0
          
